import { jsPDF } from 'jspdf';
import { Project } from '../types';
import { UserDetails } from '../components/UserDetailsForm';

const DIVINE_BLUE = '#1a365d';
const DIVINE_GOLD = '#eab308';

export const generateProjectPDF = (project: Project, userDetails: UserDetails | null) => {
  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  // Add fonts
  pdf.setFont("helvetica", "bold");

  // Header
  pdf.setFillColor(DIVINE_BLUE);
  pdf.rect(0, 0, 210, 40, 'F');
  
  // Divine Infotec Logo Text
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(24);
  pdf.text('DIVINE INFOTECH', 20, 20);
  pdf.setFontSize(12);
  pdf.text('Project Specification Document', 20, 30);

  // Current Date
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });
  pdf.setFontSize(10);
  pdf.text(date, 150, 30);

  // Gold Accent Line
  pdf.setFillColor(DIVINE_GOLD);
  pdf.rect(0, 40, 210, 2, 'F');

  // User Details Section
  pdf.setTextColor(0, 0, 0);
  pdf.setFontSize(12);
  pdf.text('Generated for:', 20, 55);
  if (userDetails) {
    pdf.setFont("helvetica", "normal");
    pdf.text(userDetails.name, 20, 62);
    pdf.text(userDetails.collegeName, 20, 69);
    pdf.text(`Year: ${userDetails.year}`, 20, 76);
  }

  // Project Title
  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(18);
  pdf.setTextColor(DIVINE_BLUE);
  pdf.text(project.title, 20, 95);

  // Project Details
  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(12);
  pdf.setTextColor(0, 0, 0);

  // Description
  pdf.setFont("helvetica", "bold");
  pdf.text('Project Description:', 20, 110);
  pdf.setFont("helvetica", "normal");
  const descriptionLines = pdf.splitTextToSize(project.description, 170);
  pdf.text(descriptionLines, 20, 117);

  // Tech Stack
  pdf.setFont("helvetica", "bold");
  pdf.text('Technology Stack:', 20, 140);
  pdf.setFont("helvetica", "normal");
  const techStack = project.stack.join(', ');
  const techStackLines = pdf.splitTextToSize(techStack, 170);
  pdf.text(techStackLines, 20, 147);

  // Project Features
  pdf.setFont("helvetica", "bold");
  pdf.text('Key Features:', 20, 165);
  pdf.setFont("helvetica", "normal");
  let yPos = 172;
  (project.features || [
    "Basic project setup and configuration",
    "Core functionality implementation",
    "User interface development",
    "Testing and documentation"
  ]).forEach((feature) => {
    pdf.text('• ' + feature, 25, yPos);
    yPos += 7;
  });

  // Project Metadata
  pdf.setFillColor(245, 245, 245);
  pdf.rect(20, yPos + 10, 170, 30, 'F');
  pdf.setFont("helvetica", "bold");
  pdf.text('Project Metadata:', 25, yPos + 20);
  pdf.setFont("helvetica", "normal");
  pdf.text(`Difficulty: ${project.difficulty}`, 25, yPos + 27);
  pdf.text(`Duration: ${project.duration || '2-4 weeks'}`, 85, yPos + 27);
  pdf.text(`Team Size: ${project.teamSize || '1-2 developers'}`, 25, yPos + 34);
  pdf.text(`Complexity: ${project.complexity || 'Medium'}`, 85, yPos + 34);

  // Footer
  pdf.setFillColor(DIVINE_BLUE);
  pdf.rect(0, 277, 210, 20, 'F');
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(10);
  pdf.text('Generated by Divine Infotec Project Generator', 20, 287);
  pdf.text('www.divineinfotec.com', 150, 287);

  // Security Watermark
  pdf.setTextColor(220, 220, 220);
  pdf.setFontSize(60);
  pdf.setFont("helvetica", "bold");
  pdf.save(`divine-project-${project.title.toLowerCase().replace(/\s+/g, '-')}.pdf`);
}; 